---
title: "Nécessité de détailler la mesure du développement humain (IDH & IDHI)"
author: "Laurine KOMENDANCZYK & Yannis BARBA"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: columns
    vertical_layout: fill
    navbar:
      - { icon: "fa-github", href: "https://github.com/AgrocampusDS/visualisation-laurine-yannis", align: right }
      - { icon: "fa-kip-sign", href: "https://www.kaggle.com/datasets/sudhirnl7/human-development-index-hdi", align: right, style: "color:white;" }
params:
  setup_path: ../resources/
---

<style>                     
.navbar {
  background-color:#463E33;
  border-color:#46ACC8;
}
.navbar-brand {
color:white!important;
}

.navbar-author{
display:none;
}

icon {
  color: white;
}


</style>   


```{r setup, include=FALSE}
library('flexdashboard')
library('plotly')
library('tidyverse')
library('ggplot2')
library("ggthemes")
library("gridExtra")
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library("ggnewscale")
library("fmsb")
```

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

```{r}
data <- read.csv("./dataset/HDI.csv", sep=",", header = TRUE)
world <- ne_countries(scale = "medium", returnclass = "sf")

## Data pre-processing : rename of certain value
data[data$Country == "Congo (Democratic Republic of the)", "Country"] <- "Democratic Republic of the Congo"
data[data$Country == "Congo", "Country"] <- "Republic of Congo"
data[data$Country == "Tanzania (United Republic of)", "Country"] <- "Tanzania"
data[data$Country == "Bolivia (Plurinational State of)", "Country"] <- "Bolivia"
data[data$Country == "Korea (Republic of)", "Country"] <- "Republic of Korea" 

complete_data <- world %>% rename(Country = name_long) %>% inner_join(data, by="Country")

## Focus on africa

africa_data <- complete_data %>% filter(continent == "Africa")

## extract centroid 
sf_use_s2(FALSE)
countries_centroid <- st_centroid(africa_data$geometry)

africa_data <- cbind(africa_data, centroid = st_centroid(africa_data$geometry)) 

# computation of the indexes composing hdi
dta.hdi <- data.frame(africa_data[,c("Life.expectancy", 
                                     "Mean.years.of.schooling",
                                     "Gross.national.income..GNI..per.capita", 
                                     "Inequality.adjusted.life.expectancy.index", 
                                     "Inequality.adjusted.education.index",
                                     "Inequality.adjusted.income.index")])[,-7]

dta.hdi <- data.frame(c(dta.hdi, 
                        IESP = (dta.hdi[1] - 25)/(85 - 25),
                        INI = dta.hdi[2]/15, 
                        IPIB = (log(dta.hdi[3])-log(100)) /(log(40000) -log(100))))

rownames(dta.hdi) <- africa_data$sovereignt


# -- DATASET GRAPH 3 --

dta.g3 <- data.frame(africa_data[,c("Inequality.in.education...",
                         "Inequality.in.income....", 
                         "Inequality.in.life.expectancy.....2010.2015", 
                         "Gender.Development.Index.value")])[,-5]

rownames(dta.g3) <- africa_data$sovereignt

max.min = data.frame(rbind (c(100,100,100, 1), c(0,0,0,0)))
colnames(max.min) <- colnames(dta.g3)


dta.g3.CAR <- rbind(max.min, dta.g3["Central African Republic",])
dta.g3.MOR <- rbind(max.min, dta.g3["Morocco",])
dta.g3.NIG <- rbind(max.min, dta.g3["Niger",])
dta.g3.RSA <- rbind(max.min, dta.g3["South Africa",])

# Changement des noms de colonnes
colnames(dta.g3.CAR) <- c("Education", 
                          "Revenus", 
                          "Espérance de vie", 
                          "GDI")
colnames(dta.g3.MOR) <- c("Education", 
                          "Revenus", 
                          "Espérance de vie",
                          "GDI")
colnames(dta.g3.NIG) <- c("Education", 
                          "Revenus", 
                          "Espérance de vie",
                          "GDI")
colnames(dta.g3.RSA) <- c("Education", 
                          "Revenus", 
                          "Espérance de vie",
                          "GDI")

```

```{r}
## Utils

mainTitle <- function(title, bgcolor){
  return(ggplot() +                      # Draw ggplot2 plot with text only
           annotate("text",
                    x = 1,
                    y = 0,
                    size = 7,
                    fontface=2,
                    label = title) + 
           theme_void()+
           theme(plot.background = element_rect(fill=bgcolor, color=bgcolor))
  )
}
```



```{r}
# create HDI class for a better representation
africa_data <- africa_data %>% drop_na(HDI)
HDISummary <- summary(africa_data$HDI)

HDIClass <- apply(africa_data, MARGIN = 1, FUN= function(x){
  
  if(as.numeric(x["HDI"]) <= HDISummary["1st Qu."]){
    return("TB")
  }
  if((as.numeric(x["HDI"]) > HDISummary["1st Qu."]) && (as.numeric(x["HDI"]) <=HDISummary["Median"])){
    return("B")
  }
  if((as.numeric(x["HDI"]) > HDISummary["Median"]) && (as.numeric(x["HDI"]) <=HDISummary["3rd Qu."])){
    return("M")
  }
  if(as.numeric(x["HDI"]) > HDISummary["3rd Qu."]){
    return("E")
  }
})

africa_data$HDIClass <- HDIClass
```


### Focus sur l'IDH

```{r}
#Calcul des limits de gradient

limitsHDI <- summary(africa_data$HDI)[c("Min.", "Max.")]
limitsIHDI <- summary(africa_data$Inequality.adjusted.HDI..IHDI.)[c("Min.", "Max.")]

limits <- c(min = min(limitsHDI["Min."], limitsIHDI["Min."]), max= max(limitsHDI["Max."], limitsIHDI["Max."]))

# old colors : "black", "#E64814", "#E9CB0D", "#9CDE3B"

# Map of HDI in Africa
map_HDI <- africa_data %>%  ggplot() + 
  geom_sf(aes(fill=HDI)) +
  scale_fill_gradientn("IDH", 
                       colors=c("#464545", "#EC6E45", "#EBD861", "#A3D15F"), 
                       limits = limits) +
  
  theme_tufte() +
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        plot.caption = element_text(hjust=0.5, vjust = 1, size=rel(1.2)))

#map_HDI


## second part of the first grahp : component of HDI

# Prenons deux pays avec un faible HDI et deux pays avec un fort HDI

#Faible
niger <- dta.hdi["Niger",]
car <- dta.hdi["Central African Republic",]

#Fort
southAfrica <- dta.hdi["South Africa",]
morocco <- dta.hdi["Morocco",]

hist.Niger <- data.frame(t(niger)[7:9,])
hist.CAR <- data.frame(t(car)[7:9,])

hist.RSA <- data.frame(t(southAfrica)[7:9,])
hist.Morocco <- data.frame(t(morocco)[7:9,])

colnames(hist.Niger) = c("value")
colnames(hist.CAR) = c("value")

colnames(hist.RSA) = c("value")
colnames(hist.Morocco) = c("value")


histoHDI <- data.frame(index = c("IESP", "INI", "IPIB","IESP", "INI", "IPIB"), 
                       rbind(hist.Niger, hist.RSA, hist.CAR, hist.Morocco))

histoHDI <- data.frame(histoHDI,
                       Country = c(rep("Niger",3), rep("Afrique du Sud (RSA)", 3), rep("République Centrafricaine", 3), rep("Maroc", 3)),
                       Class = c(rep("B",3), rep("B", 3), rep("E", 3), rep("E", 3))
                       )

indexes = rownames(histoHDI)
                       
colnames(histoHDI) <- c("index", "values", "Country")

# annotate with value of HDI
annotation <- data.frame(
   label=c("IDH : 0.35", "IDH : 0.67", "IDH : 0.35", "IDH : 0.65"),
   Country=c("Niger", "Afrique du Sud (RSA)", "République Centrafricaine", "Maroc"),
   hjust=c(0, -0.15, 0, 0.15)
)

rect <- data.frame(
  xmin = rep(0.5, 4),
  xmax = rep(3.5, 4),
  ymin = rep(-Inf, 4),
  ymax = rep(Inf, 4),
  fill=factor(c("T", "R", "T", "R"))
)

histo <- histoHDI %>% ggplot() +
  geom_col(aes(y = values, x=index, fill = index), width = 0.35) +
  scale_fill_manual(values=c("#6A5D4D", "#8E8477", "#B5ACA1"))+
  facet_wrap(~Country)+
  
  geom_text(data = annotation,
            mapping = aes(x = 2, y=0.8, label=label),
            size=3,
            )+

  theme_tufte() +
  theme(legend.position = "None",
        axis.title = element_blank(),
        panel.spacing = unit(2, "lines"),
        panel.background = element_rect(fill="#F2F2F3", colour = "white"),
        panel.border = element_blank(),
        strip.text.x = element_text(
        size = 7, color = "black", face = "bold.italic"
        ))
#histo

# Grid Extra for first visualisation

grid.arrange(
  grobs=list(map_HDI, histo),
  widths=c(1,1),
  #layout_matrix = rbind(c(1,1))
  bottom="Indice de développement humain en Afrique. \n La valeur de l'IDH seule est insuffisante pour caractériser un pays"
)

```

### Bibliographie sur l'IDH

<iframe
    src="./informationsHDI.pdf" 
    frameborder="0"
    style="overflow:hidden;height:100%;width:100%" 
    height="100%" 
    width="100%">
</iframe>



### Détails

Source : https://www.kaggle.com/datasets/sudhirnl7/human-development-index-hdi \n


Auteurs : Laurine KOMENDANCZYK & Yannis BARBA

Column {.tabset .tabset-fade}
-----------------------------------------------------------------------


### Importance de L'IDHI

```{r}
# Plot first Map, Africa HDI and School
map_IHDI <- africa_data %>%  ggplot() + 
  geom_sf(aes(fill=Inequality.adjusted.HDI..IHDI.)) +
  scale_fill_gradientn("IDHI", colors=c("#464545", "#EC6E45", "#EBD861", "#A3D15F"),
                       limits = limits) +

  scale_size(name="IDHI") +
  theme_tufte() +
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank())

#map_IHDI

africa_data$RatioIDHI_IDH <- africa_data$Inequality.adjusted.HDI..IHDI. / africa_data$HDI

country <- africa_data$Country
highlightCountries <- rep(0, length(country))

highlightCountries[which(country=="South Africa")] <- data.frame(africa_data[which(country=="South Africa"),"RatioIDHI_IDH"])[-2][1,1]

highlightCountries[which(country=="Niger")] <- data.frame(africa_data[which(country=="Niger"),"RatioIDHI_IDH"])[-2][1,1]

ratio_graph <- africa_data %>% drop_na(Inequality.adjusted.HDI..IHDI.) %>% 
  
  ggplot() +
  geom_col(aes(y=reorder(Country, RatioIDHI_IDH), x=RatioIDHI_IDH, fill=HDIClass), width = 0.95) +
  scale_fill_manual("Classes IDH", values=c("#A3D15F", "#EBD861", "#EC6E45","#464545"),
                     breaks=c("E", "M", "B","TB"), labels=c("Élevé", "Moyen", "Bas","Très Bas"))+
  
  labs(x="Ratio IDHI/IDH", y =element_blank()) +
  geom_vline(xintercept =1, color="#9CDE3B")+
  
  geom_rect(xmin=-Inf, xmax=Inf, ymin=31, ymax=42.5, color="black", alpha=0, size=0.1) +
  geom_text(x = 1.5, y = 40, size=3,
    label="Ratio élevé : \n IDH moins pénalisé") +
  
  geom_rect(xmin=-Inf, xmax=Inf, ymin=0, ymax=5, color="black", alpha=0, size=0.1) +
  geom_text(x = 1.5, y = 2.5, size=3,
    label="Ratio faible : \n IDH plus pénalisé") +
  
  geom_text(x = -0.25, y = 36, size = 2.5, label="Niger")+
  geom_text(x = -0.25, y = 33, size = 2.5, label="Maroc")+
  geom_text(x = -0.2, y = 15, size = 2.5, label="RSA")+
  geom_text(x = -0.6, y = 2, size = 2.5, label="République Centrafricaine")+
  
  theme_light()+
  theme(axis.text.x = element_text(hjust=1),
        axis.text.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_line(color = "grey",
                                  size = 0.2,
                                  linetype = 1),
        panel.border = element_blank(),
      
        ) +
  scale_x_continuous(breaks = seq(0,1, .1), 
                     labels=c("0", ".1", ".2",".3", ".4", ".5", ".6", ".7",".8", ".9", "1"),  
                     limits = c(0,1))+
  coord_cartesian(clip = "off")

#ratio_graph

grid.arrange(
  grobs=list(map_IHDI, ratio_graph),
  widths=c(1,1),
  #layout_matrix = rbind(c(1,1))
  bottom="L'Indice de développement humain ajusté aux inégalités pénalise l'IDH"
)
```



### Détails sur les inégalités

```{r}
par(mfrow = c(2,2), omi=c(0,0.25,0,0.25),oma = c(0,0,2,0),mar = c(0,0,2,0))

# =======
# South Africa

colRSA = c("#a3d15f")
areaRSA = rgb(163, 209, 95, alpha = 120, maxColorValue = 255 )

radarchart(dta.g3.RSA[-4], 
           # -- GRID --
           cglty = 2,       # Grid line type
           cglcol = "grey", # Grid line color
           
           # -- LINE -- 
           pcol = colRSA,   # Color for each line
           plwd = 2,        # Width for each line
           plty = 1 ,       # Line type for each line
           
           # -- AREA --
           pfcol = areaRSA,
           
           # -- TEXTS --
           title = "Afrique du Sud", 
           maxmin = TRUE)

text(0,1.07,paste(dta.g3.RSA[3,1], "%"), col = colRSA)
text(-1.03,-0.77,paste(dta.g3.RSA[3,2], "%"), col = colRSA)
text(1.03,-0.77,paste(dta.g3.RSA[3,3], "%"), col = colRSA)
text(1.4,0.4, paste("GDI :", dta.g3.RSA[3,4]), cex = 1, family = "sans", font = 4)


# =======
# Morocco

colMOR = c("#a3d15f")
areaMOR = rgb(163, 209, 95, alpha = 120, maxColorValue = 255 )

radarchart(dta.g3.MOR[-4], 
           # -- GRID --
           cglty = 2,       # Grid line type
           cglcol = "grey", # Grid line color
           
           # -- LINE -- 
           pcol = colMOR,   # Color for each line
           plwd = 2,        # Width for each line
           plty = 1 ,       # Line type for each line
           
           # -- AREA --
           pfcol = areaMOR,
           
           # -- TEXTS --
           title = "Maroc", 
           maxmin = TRUE)

text(0,1.07,paste(dta.g3.MOR[3,1], "%"), col = colMOR)
text(-1.03,-0.77,paste(dta.g3.MOR[3,2], "%"), col = colMOR)
text(1.03,-0.77,paste(dta.g3.MOR[3,3], "%"), col = colMOR)
text(1.4,0.4, paste("GDI :", dta.g3.MOR[3,4], "%"), cex = 1, family = "sans", font = 4)

# =======
# Niger

colNIG = c("#464545")
areaNIG = rgb(70, 69, 69, alpha = 120, maxColorValue = 255 )

radarchart(dta.g3.NIG[-4], 
           # -- GRID --
           cglty = 2,       # Grid line type
           cglcol = "grey", # Grid line color
           
           # -- LINE -- 
           pcol = colNIG,   # Color for each line
           plwd = 2,        # Width for each line
           plty = 1 ,       # Line type for each line
           
           # -- AREA --
           pfcol = areaNIG,
           
           # -- TEXTS --
           title = "Niger", 
           maxmin = TRUE)

text(0,1.07,paste(dta.g3.NIG[3,1], "%"), col = colNIG)
text(-1.03,-0.77,paste(dta.g3.NIG[3,2], "%"), col = colNIG)
text(1.03,-0.77,paste(dta.g3.NIG[3,3],"%"), col = colNIG)
text(1.4,0.4, paste("GDI :", dta.g3.NIG[3,4]), cex = 1, family = "sans", font = 4)

# =========================
# Central African Republic 

colCAR = c("#464545")
areaCAR = rgb(70, 69, 69, alpha = 120, maxColorValue = 255 )

radarchart(dta.g3.CAR[-4], 
           # -- GRID --
           cglty = 2,       # Grid line type
           cglcol = "grey", # Grid line color
           
           # -- LINE -- 
           pcol = colCAR,   # Color for each line
           plwd = 2,        # Width for each line
           plty = 1 ,       # Line type for each line
           
           # -- AREA --
           pfcol = areaCAR,
           
           # -- TEXTS --
           title = "République Centrafricaine",
           maxmin = TRUE)

text(0,1.07,paste(dta.g3.CAR[3,1], "%"), col = colCAR)
text(-1.03,-0.77,paste(dta.g3.CAR[3,2],"%"), col = colCAR)
text(1.03,-0.77,paste(dta.g3.CAR[3,3], "%"), col = colCAR)
text(1.4,0.4, paste("GDI :", dta.g3.CAR[3,4]), cex = 1, family = "sans", font = 4)

```

